---
networks:
    net1:
        external_connectivity: no
        name: "data"
        ip_address: "192.168.24.254"
        netmask: "255.255.255.0"
        nic: enp6s0f1 #Extra
        forward: bridge #Extra
    net2:
        external_connectivity: yes
        name: "management"
        ip_address: "172.16.0.1"
        netmask: "255.255.255.0"
        forward: nat
        dhcp:
            range:
                start: "172.16.0.2"
                end: "172.16.0.100"
            subnet_cidr: "172.16.0.0/24"
            subnet_gateway: "172.16.0.1"
        floating_ip:
            start: "172.16.0.101"
            end: "172.16.0.150"
    net3:
        external_connectivity: yes
        name: "external"
        forward: bridge
        ip_address: "10.46.23.129"
        netmask: "255.255.255.192"
        nic: enp6s0f0.316

nodes:
    default:
        interfaces:
            - network: "data"
            - network: "management"
            - network: "external"
        external_network:
            network: "management"
    novacontrol:
        interfaces:
            - network: "data"
            - network: "management"
        external_network:
            network: "management"
    odl:
        interfaces:
            - network: "management"
        external_network:
            network: "management"
    cfme:
        interfaces:
            - network: "external"
            - network: "data"
        external_network:
            network: "external"
    cfme_tester:
        interfaces:
            - network: "external"
            - network: "data"
        external_network:
            network: "external"
