# The following structure used for the hybrid deployments,
# where Undercloud and Controllers are virtual, Computes baremetal
# and the networks are bridged outside of the local hypervisor host.
# The separation of the networks are the following:
# * br-ctlplane
# * br-external
# * br-management
---
networks:
    net1:
        name: br-ctlplane
        forward: bridge
        nic: enp6s0f1
        ip_address: 192.168.24.150
        netmask: 255.255.255.0
    net2:
        name: "external"
        forward: bridge

        # if there's an IP assigned to this bridge but no vlan ID is set on it (see explanation about 'nic:' below) the communication will still not work so
        # there's no point of having IP on this bridge on the hypervisor
        # ip_address: "10.46.23.129"
        # netmask: "255.255.255.192"

        # the hypervisor should have only a real physical NIC attached here (not a vlaned nic), otherwise the packets will be encapsulated in vlan twice:
        # once inside the controller-0 then by the nic on the hypervisor causing things not to work
        nic: enp6s0f0

        # NOTE: make sure there is _not_ a vlan interface created on the NIC that's connected to the VLANed external network otherwise that vlan interface will be
        # catching all the traffic instead of the traffic coming down the 'external' bridge (and to overcloud controllers)
    net3:
        external_connectivity: yes
        name: "management"
        ip_address: "172.16.0.1"
        netmask: "255.255.255.0"
        forward: nat
        dhcp:
            range:
                start: "172.16.0.2"
                end: "172.16.0.100"
            subnet_cidr: "172.16.0.0/24"
            subnet_gateway: "172.16.0.1"
        floating_ip:
            start: "172.16.0.101"
            end: "172.16.0.150"

nodes:
    undercloud:
        interfaces:
            - network: "br-ctlplane"
              bridged: yes
            - network: "management"
        external_network:
            network: "management"
    controller:
        interfaces:
            - network: "br-ctlplane"
              bridged: yes
            - network: "external"
              bridged: yes
            - network: "management"
        external_network:
            network: "management"
