---
parameter_defaults:
    OpenDaylightFeatures: [odl-mdsal-trace, odl-netvirt-openstack, odl-jolokia]
    OpenDaylightLogMechanism: 'file'
    ExtraConfig:
      opendaylight::log_levels:
        org.opendaylight.openflowplugin.impl: 'TRACE'
      opendaylight::log_max_rollover: 50
