---
parameter_defaults:
    Debug: true
    ConfigDebug: true
    OpenDaylightLogMechanism: 'file'
    ExtraConfig:
      opendaylight::log_levels:
        org.opendaylight.openflowplugin.impl: 'TRACE'
        org.opendaylight.mdsal.impl: 'TRACE'
      opendaylight::log_max_rollover_config: 50
      opendaylight::extra_features: 'odl-mdsal-trace,odl-netvirt-openstack'
