parameter_defaults:
  # Add PciPassthroughFilter to the scheduler default filters
  NovaSchedulerDefaultFilters: ['RetryFilter','AvailabilityZoneFilter','RamFilter','ComputeFilter','ComputeCapabilitiesFilter','ImagePropertiesFilter','ServerGroupAntiAffinityFilter','ServerGroupAffinityFilter','PciPassthroughFilter']
  NovaSchedulerAvailableFilters: ["nova.scheduler.filters.all_filters","nova.scheduler.filters.pci_passthrough_filter.PciPassthroughFilter"]

  NeutronPhysicalDevMappings: "datacentre:ens2f0"

  # Number of VFs that needs to be configured for a physical interface
  NeutronSriovNumVFs: "ens2f0:5"

  NovaPCIPassthrough:
    - devname: "ens2f0"
      physical_network: "datacentre"
