---
- name: undercloud post provision
  hosts: undercloud
  become: true
  tasks:
    - name: Setting up interface for public API on undercloud
      shell: ifup "{{odl.public_interface.address}}{{odl.public_interface.vlan}}"
